# Generated by Django 3.1.1 on 2024-12-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0002_auto_20241205_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
