# Generated by Django 3.1.1 on 2024-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0003_auto_20241206_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
