# Generated by Django 3.1.1 on 2024-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0004_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='', max_length=13),
        ),
    ]
