# Generated by Django 3.1.1 on 2024-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0005_auto_20241206_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
