# Generated by Django 3.1.1 on 2024-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0007_auto_20241206_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
