# Generated by Django 3.1.1 on 2024-12-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0010_auto_20241207_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
