# Generated by Django 3.1.1 on 2024-12-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0012_payment_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_details',
            options={'verbose_name_plural': 'payment_details'},
        ),
    ]
