# Generated by Django 3.1.1 on 2024-12-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0013_auto_20241210_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='selected_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitabu_stop_app.product'),
        ),
    ]
