# Generated by Django 3.1.1 on 2024-12-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0014_auto_20241210_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/resource_upload/')),
                ('document', models.FileField(upload_to='doc/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitabu_stop_app.user')),
            ],
        ),
    ]
