# Generated by Django 3.1.1 on 2024-12-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0015_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_details',
        ),
    ]
