# Generated by Django 3.1.1 on 2024-12-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0016_delete_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.FileField(upload_to='file_uploads/'),
        ),
    ]
