# Generated by Django 3.1.1 on 2024-12-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0017_auto_20241210_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
    ]
