# Generated by Django 3.1.1 on 2024-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0018_remove_resource_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.FileField(upload_to='documentation/'),
        ),
    ]
