# Generated by Django 3.1.1 on 2024-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabu_stop_app', '0019_auto_20241211_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
